apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      name: {{ .Release.Name }}
      labels:
        app: {{ .Release.Name }}
    spec:
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: {{ .Release.Name }}
          env:
            - name: ZOCALO_CONFIG
              value: {{ .Values.zocalo.config | quote }}
            - name: FFS_QUEUE
              value: {{ .Values.zocalo.queue | quote }}
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- include "ffs.resources" . | nindent 10 }}
          {{- if .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- end }}
          {{- include "ffs.volumeMounts" (dict "Values" .Values "readOnlyDls" true) | nindent 10 }}
      {{- include "ffs.nodeSelector" . | nindent 6 }}
      {{- include "ffs.tolerations" . | nindent 6 }}
      {{- include "ffs.volumes" . | nindent 6 }}
