#include "connected_components.hpp"

#include <builtin_types.h>

#include <boost/graph/adjacency_list.hpp>
#include <boost/graph/connected_components.hpp>
#include <cstdint>
#include <vector>

#include "common.hpp"
#include "cuda_common.hpp"
#include "h5read.h"

ConnectedComponents::ConnectedComponents(const uint8_t *result_image,
                                         const pixel_t *original_image,
                                         const ushort width,
                                         const ushort height,
                                         const uint32_t min_spot_size)
    : num_strong_pixels(0), num_strong_pixels_filtered(0) {
    // Construct signals
    size_t k = 0;  // Linear index for the image
    for (int y = 0; y < height; ++y) {
        for (int x = 0; x < width; ++x, ++k) {
            if (result_image[k]) {  // Store only non-zero (signal) pixels
                int2 coord{x, y};
                signals[k] = {coord, original_image[k], k};
                ++num_strong_pixels;
            }
        }
    }

    // Build graph
    build_graph(width, height);

    // Generate bounding boxes
    generate_boxes(width, height, min_spot_size);
}

/**
 * Build a graph from the pixel coordinates
 * 
 * The graph is built by iterating over the pixel coordinates and connecting
 * pixels that are adjacent to each other.
 */
void ConnectedComponents::build_graph(const ushort width, const ushort height) {
    // Map linear_index to vertex ID for graph consistency
    size_t vertex_id = 0;

    // First, add vertices to the graph
    for (const auto &[linear_index, signal] : signals) {
        vertex_map[linear_index] = vertex_id++;
        boost::add_vertex(graph);
    }

    // Add edges by checking neighbors
    for (const auto &[linear_index, signal] : signals) {
        size_t right_linear_index = linear_index + 1;      // Pixel to the right
        size_t below_linear_index = linear_index + width;  // Pixel below

        // Check and connect to the pixel on the right
        if (signals.find(right_linear_index) != signals.end()) {
            boost::add_edge(
              vertex_map[linear_index], vertex_map[right_linear_index], graph);
        }

        // Check and connect to the pixel below
        if (signals.find(below_linear_index) != signals.end()) {
            boost::add_edge(
              vertex_map[linear_index], vertex_map[below_linear_index], graph);
        }
    }
}

/**
 * Generate bounding boxes from the connected components
 * 
 * The bounding boxes are generated by iterating over the labels and pixel
 * coordinates and updating the bounding box for each label.
 */
void ConnectedComponents::generate_boxes(const ushort width,
                                         const ushort height,
                                         const uint32_t min_spot_size) {
    auto labels = std::vector<int>(boost::num_vertices(graph));
    auto num_labels = boost::connected_components(graph, labels.data());

    // Initialize bounding boxes
    boxes = std::vector<Reflection>(num_labels, {width, height, 0, 0});

    // Iterate over the signals and update the bounding boxes
    for (const auto &[linear_index, signal] : signals) {
        // Retrieve the vertex index for this linear_index (linear_index -> vertex_id in build_graph)
        auto vertex_it = vertex_map.find(linear_index);
        if (vertex_it == vertex_map.end()) {
            throw std::runtime_error("Vertex not found in vertex_map");
        }

        size_t vertex_id = vertex_it->second;  // Vertex ID in the graph
        int label = labels[vertex_id];         // Label assigned to this vertex

        auto &box = boxes[label];
        box.l = std::min(box.l, signal.coord.x);
        box.r = std::max(box.r, signal.coord.x);
        box.t = std::min(box.t, signal.coord.y);
        box.b = std::max(box.b, signal.coord.y);
        ++box.num_pixels;  // Increment the number of pixels in the box
    }

    // Filter boxes based on the minimum spot size
    if (min_spot_size > 0) {
        std::vector<Reflection> filtered_boxes;
        for (auto &box : boxes) {
            if (box.num_pixels >= min_spot_size) {
                filtered_boxes.emplace_back(box);
                num_strong_pixels_filtered += box.num_pixels;
            }
        }
        // Overwrite boxes with filtered boxes
        boxes = std::move(filtered_boxes);
    } else {
        num_strong_pixels_filtered = num_strong_pixels;
    }
}

std::vector<Reflection3D> ConnectedComponents::find_3d_components(
  const std::vector<std::unique_ptr<ConnectedComponents>> &slices,
  const ushort width,
  const ushort height) {
    // Step 1: Initialize the 3D graph and vertex mapping
    // ----------------------------------------------
    // The 3D graph will combine all the 2D graphs (one per slice)
    // and add inter-slice (z-axis) edges. Each vertex in the graph
    // represents a pixel in the dataset, and edges represent connectivity
    // between pixels (either within a slice or across slices).
    printf("Initializing 3D graph...\n");
    boost::adjacency_list<boost::vecS, boost::vecS, boost::undirectedS> graph;
    std::vector<std::unordered_map<size_t, size_t>>
      slice_vertex_maps;   // Slice-specific vertex mappings
    size_t vertex_id = 0;  // Global vertex ID for the 3D graph

    // Add vertices for each slice
    printf("Adding vertices to 3D graph...\n");
    for (const auto &connected_component : slices) {
        const auto &slice_graph =
          connected_component->get_graph();  // 2D graph of the slice
        const auto &signals =
          connected_component->get_signals();  // Signals (pixels with intensity)

        std::unordered_map<size_t, size_t>
          vertex_map;  // Map from 2D graph vertices to 3D graph vertices

        // Add each vertex from the 2D graph to the 3D graph
        for (const auto &vertex :
             boost::make_iterator_range(boost::vertices(slice_graph))) {
            vertex_map[vertex] = vertex_id++;  // Assign a unique global ID
            boost::add_vertex(graph);          // Add the vertex to the 3D graph
        }

        slice_vertex_maps.push_back(
          std::move(vertex_map));  // Store the mapping for this slice
    }

    // Step 2: Add edges for in-slice connectivity
    // ----------------------------------------------
    // These edges represent the connectivity within each individual slice,
    // as already computed in the 2D graph.
    printf("Adding in-slice connectivity to 3D graph...\n");
    for (size_t slice_idx = 0; slice_idx < slices.size(); ++slice_idx) {
        const auto &slice_graph = slices[slice_idx]->get_graph();  // 2D graph
        const auto &vertex_map =
          slice_vertex_maps[slice_idx];  // Mapping for this slice

        // Add each edge from the 2D graph to the 3D graph
        for (const auto &edge : boost::make_iterator_range(boost::edges(slice_graph))) {
            auto source =
              boost::source(edge, slice_graph);  // Source vertex in 2D graph
            auto target =
              boost::target(edge, slice_graph);  // Target vertex in 2D graph
            boost::add_edge(vertex_map.at(source),
                            vertex_map.at(target),
                            graph);  // Add edge to 3D graph
        }
    }

    // Step 3: Add inter-slice (z-axis) connectivity
    // ----------------------------------------------
    // These edges connect corresponding pixels in adjacent slices
    // (i.e., pixels with the same linear index in the signal map).
    printf("Adding inter-slice connectivity to 3D graph...\n");
    for (size_t slice_idx = 0; slice_idx < slices.size() - 1; ++slice_idx) {
        const auto &signals_curr =
          slices[slice_idx]->get_signals();  // Signals in the current slice
        const auto &signals_next =
          slices[slice_idx + 1]->get_signals();  // Signals in the next slice
        const auto &vertex_map_curr =
          slice_vertex_maps[slice_idx];  // Vertex map for the current slice
        const auto &vertex_map_next =
          slice_vertex_maps[slice_idx + 1];  // Vertex map for the next slice

        // Check for matching pixels in adjacent slices and add edges
        for (const auto &[linear_index, signal] : signals_curr) {
            if (signals_next.find(linear_index) != signals_next.end()) {
                boost::add_edge(
                  vertex_map_curr.at(linear_index),  // Current slice vertex
                  vertex_map_next.at(linear_index),  // Next slice vertex
                  graph);                            // Add edge to 3D graph
            }
        }
    }

    // Step 4: Perform connected components analysis on the 3D graph
    // ----------------------------------------------
    // Use the Boost library to identify connected components in the 3D graph.
    // Each connected component corresponds to a 3D cluster of connected pixels.
    printf("Performing connected components analysis on 3D graph...\n");
    std::vector<int> labels(
      boost::num_vertices(graph));  // Component ID for each vertex
    int num_components =
      boost::connected_components(graph, labels.data());  // Find connected components

    // Group vertices into their respective connected components
    printf("Grouping vertices into connected components...\n");
    std::vector<std::vector<size_t>> components(
      num_components);  // Each component is a list of vertices
    for (size_t slice_idx = 0; slice_idx < slices.size(); ++slice_idx) {
        const auto &signals =
          slices[slice_idx]->get_signals();  // Signals in this slice
        const auto &vertex_map =
          slice_vertex_maps[slice_idx];  // Vertex mapping for this slice

        // Assign each signal pixel to its connected component
        for (const auto &[linear_index, signal] : signals) {
            size_t unique_index =
              slice_idx * width * height + linear_index;  // Unique global index
            size_t graph_vertex =
              vertex_map.at(linear_index);  // Vertex in the 3D graph
            components[labels[graph_vertex]].push_back(
              unique_index);  // Add to the appropriate component
        }
    }

    // Step 5: Generate 3D reflections
    // ----------------------------------------------
    // For each connected component, compute the bounding box, pixel count,
    // and weighted center of mass based on pixel intensities.
    printf("Generating 3D reflections...\n");
    std::vector<Reflection3D> reflections_3d;

    for (const auto &component : components) {
        if (component.empty()) continue;  // Skip empty components

        Reflection3D reflection = {
          INT_MAX, INT_MAX, INT_MAX, 0, 0, 0, 0, 0.0, 0.0, 0.0};
        double total_intensity = 0.0;

        // Process each pixel in the component
        for (size_t unique_index : component) {
            int slice = unique_index / (width * height);  // Slice index
            size_t linear_index =
              unique_index % (width * height);  // Linear index within the slice

            const auto &signal =
              slices[slice]->get_signals().at(linear_index);  // Signal data

            // Update bounding box
            reflection.xmin = std::min(reflection.xmin, signal.coord.x);
            reflection.ymin = std::min(reflection.ymin, signal.coord.y);
            reflection.zmin = std::min(reflection.zmin, slice);
            reflection.xmax = std::max(reflection.xmax, signal.coord.x);
            reflection.ymax = std::max(reflection.ymax, signal.coord.y);
            reflection.zmax = std::max(reflection.zmax, slice);

            // Accumulate intensity and weighted coordinates
            double intensity = static_cast<double>(signal.intensity);
            total_intensity += intensity;
            reflection.cx += intensity * signal.coord.x;
            reflection.cy += intensity * signal.coord.y;
            reflection.cz += intensity * slice;
            ++reflection.num_pixels;  // Count pixels
        }

        // Normalize weighted coordinates
        if (total_intensity > 0) {
            reflection.cx /= total_intensity;
            reflection.cy /= total_intensity;
            reflection.cz /= total_intensity;
        }

        reflections_3d.push_back(reflection);  // Add the reflection to the list
    }

    return reflections_3d;
}
